// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverlayStatus() {
  return window['go']['main']['App']['GetOverlayStatus']();
}

export function SendTestEvent(arg1) {
  return window['go']['main']['App']['SendTestEvent'](arg1);
}

export function StartOverlayServer(arg1) {
  return window['go']['main']['App']['StartOverlayServer'](arg1);
}

export function StopOverlayServer() {
  return window['go']['main']['App']['StopOverlayServer']();
}
