// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOverlayStatus():Promise<main.OverlayStatus>;

export function SendTestEvent(arg1:string):Promise<void>;

export function StartOverlayServer(arg1:number):Promise<void>;

export function StopOverlayServer():Promise<void>;
