// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginTwitchAuth(arg1) {
  return window['go']['main']['App']['BeginTwitchAuth'](arg1);
}

export function BeginYouTubeAuth(arg1) {
  return window['go']['main']['App']['BeginYouTubeAuth'](arg1);
}

export function ConnectTwitch(arg1) {
  return window['go']['main']['App']['ConnectTwitch'](arg1);
}

export function ConnectYouTube(arg1) {
  return window['go']['main']['App']['ConnectYouTube'](arg1);
}

export function DisconnectTwitch() {
  return window['go']['main']['App']['DisconnectTwitch']();
}

export function DisconnectYouTube() {
  return window['go']['main']['App']['DisconnectYouTube']();
}

export function GetOverlayStatus() {
  return window['go']['main']['App']['GetOverlayStatus']();
}

export function GetTwitchStatus() {
  return window['go']['main']['App']['GetTwitchStatus']();
}

export function GetYouTubeStatus() {
  return window['go']['main']['App']['GetYouTubeStatus']();
}

export function SendTestEvent(arg1) {
  return window['go']['main']['App']['SendTestEvent'](arg1);
}

export function SignOutTwitch() {
  return window['go']['main']['App']['SignOutTwitch']();
}

export function SignOutYouTube() {
  return window['go']['main']['App']['SignOutYouTube']();
}

export function StartOverlayServer(arg1) {
  return window['go']['main']['App']['StartOverlayServer'](arg1);
}

export function StopOverlayServer() {
  return window['go']['main']['App']['StopOverlayServer']();
}
